# This is a basic workflow to help you get started with Actions

name: Scheduled v2

on:
  schedule:
    - cron: "22 19 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coverity-scan:
    name: Scan with Coverity
    # only run the workflow on Squid's main repository
    if: github.repository == 'squid-cache/squid'

    runs-on: ubuntu-22.04
    # this job only runs if the github repository contains username
    # and password to access the Coverity Scan service
    env:
      coverity_user: ${{ secrets.COVERITY_USER }}
      coverity_token: ${{ secrets.COVERITY_TOKEN }}

    container:
      image: squidcache/buildfarm-coverity:stable
      options: --user 1001 # uid used by worfklow runner

    steps:
      - name: Checkout Sources
        if: env.coverity_user && env.coverity_token
        uses: actions/checkout@v4

      - name: Scan
        if: env.coverity_user && env.coverity_token
        run: |
          cov-build --dir cov-int ./test-builds.sh layer-02-maximus
          tar caf cov-int.tar.xz cov-int
          curl \
            --form email=${coverity_user} \
            --form token=${coverity_token} \
            --form version=coverity_scan \
            --form file=@cov-int.tar.xz \
            https://scan.coverity.com/builds?project=Squid
          true # ignore curl exit code
